### ISSUE TITLE
v1.3.1 - Header menus display below the lightGallery component

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-themes/foundation-s#48]
Hello,

I'm fiddling with the recent pre-version v1.3.1 release and when using the lightgallery item page block (now core in Omeka S v4.0.0-rc) in conjunction with the default stylesheet from the foundation-s theme, the hover menus display below the media component.

Here is a capture of the issue, where the Collections menu is not displaying over the content as expected.
<img width="500" alt="Capture d’écran 2022-12-21 à 16 08 19" src="https://user-images.githubusercontent.com/3284234/208937653-0324c5c3-0005-4e2d-82a9-8e6dfbd1c551.png">

I guess this is a matter of setting the right z-index for either the menus or the gallery, but I'm a bit confused which one exactly.

Thanks in advance and kind regards

Laurent

**Comment by kimisgold** [comment]
Fixed in v1.3.3

**Comment by ManOnDaMoon** [comment]
Hello @kimisgold 

I'm reopening this as the issue is still present in v1.3.3

The `z-index: 2;` applied on `.is-submenu` displays the menu above the LightGallery background now, but still below the pictures themselves, and the sub-menu hover events are not triggered either.

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/3284234/219157468-6c25e12d-8a7b-4477-93c3-f4e01284fa34.png">

From my own tests, `z-index: 3;` seems to be the magic number here, even if I dont grasp the logic behind it.
